raw_file = "Utah_teapot_solid.raw"

resolution.x = 238
resolution.y = 151
resolution.z = 126

[voxel]
sample_type = "unsigned char"
endianness = "little"
size.x = 0.080000
size.y = 0.080000
size.z = 0.080000

[voxel.value]
AIR=0
SKIN6=255
SKIN18=254
SKIN26=253
MODEL=252

[scene.bounding_box]
min.x = -9.000000
min.y = -6.000000
min.z = -1.000000
max.x = 10.000000
max.y = 6.000000
max.z = 9.000000
unit = "meter"
