raw_file = "vase01.raw"
[resolution]
x = 172
y = 172
z = 322

[voxel]
sample_type = "unsigned char"
endianness = "little"

AIR=0
SKIN6=255
SKIN18=254
SKIN26=253
MODEL=252

[voxel.size]
x = 0.010000
y = 0.010000
z = 0.010000
